export { default as about1 } from './about1.jpg'
export { default as medical1 } from './medical1.png'
export { default as coxmind } from './coxmind.jpeg'
export { default as glyrosun } from './glyrosun.jpeg'
export { default as nyramind } from './Nyramind.jpeg'
export { default as seizmex } from './seizmex.jpeg'
export { default as setmind } from './setmind.jpg'
export { default as stromind } from './stromind.jpeg'
export { default as telotel } from './Telotel.jpeg'
export { default as walmindDSR } from './walmindDSR.jpeg'
export { default as walmindDSR2 } from './walmindDSR2.jpg'
export { default as injection } from './locosunt.jpg'
export { default as injection2 } from './locosant2.jpeg'
export { default as injection3 } from './locosunt3.webp'
export { default as about } from './about.png.webp'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'
// export { default as medical1 } from './medical1.png'



